# Generated by Django 4.1.4 on 2022-12-22 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0002_rename_title_title_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Todo',
        ),
    ]
