# Generated by Django 4.1.4 on 2022-12-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0003_rename_title_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='title',
        ),
    ]
